CrudCliente/Models/BancoContext.cs
using Microsoft.EntityFrameworkCore;

namespace CrudCliente.Models
{
    public class BancoContext : DbContext
    {
        public BancoContext(DbContextOptions<BancoContext> options) : base(options)

        {

        }
        public DbSet <Cliente> Clientes {get;set; }     
        }
    }

CrudCliente/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrudCliente.Models
{
    [Table("Cliente")]
    public class Cliente
    {
        [Key]
        public int ID { get; set; }
        public string Nome { get; set; }
        [EmailAddress(ErrorMessage = "Email Inválido")]
        public string Email { get; set; }
        [Display(Name ="Endereço")]
        public string Endereco { get; set; }
        public string Contato { get; set;}

    }
}

CrudCliente/Models/ErrorViewModel.cs
namespace CrudCliente.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudCliente/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudCliente.Models;

namespace CrudCliente.Controllers
{
    public class ClientesController : Controller
    {
        private readonly BancoContext _context;

        public ClientesController(BancoContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
              return _context.Clientes != null ? 
                          View(await _context.Clientes.ToListAsync()) :
                          Problem("Entity set 'BancoContext.Clientes'  is null.");
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Email,Endereco,Contato")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Email,Endereco,Contato")] Cliente cliente)
        {
            if (id != cliente.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clientes == null)
            {
                return Problem("Entity set 'BancoContext.Clientes'  is null.");
            }
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
          return (_context.Clientes?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

CrudCliente/Controllers/HomeController.cs
using CrudCliente.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudCliente.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudCliente/Views/Clientes/Create.cshtml
@model CrudCliente.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1 class="mb-3">Inserção de Cliente</h1>
<h4>Novo Cliente</h4>
<hr />
<div class="row">
    <div class="d-grid gap-3">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="input-group p-3 col gap-3 d-grid">

                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Nome" class="input-group-text"></label>
                    <input asp-for="Nome" class="form-control" />
                </div>

                <span asp-validation-for="Nome" class="text-danger"></span>

                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Email" class="input-group-text"></label>
                    <input asp-for="Email" class="form-control" />  
                </div>

                <span asp-validation-for="Email" class="text-danger"></span>

                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Endereco" class="input-group-text"></label>
                    <input asp-for="Endereco" class="form-control" />
                </div>

                <span asp-validation-for="Endereco" class="text-danger"></span>

                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Contato" class="input-group-text"></label>
                    <input asp-for="Contato" class="form-control" />
                </div>         
                
                <span asp-validation-for="Contato" class="text-danger"></span>

            </div>

            <div class="grid gap-3 row">
                <input type="submit" value="Inserir" class="btn btn-primary p-2 g-col-3 w-25" />
                <a asp-action="Index" class="btn btn-outline-primary p-2 g-col-3 w-25">Voltar </a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudCliente/Views/Clientes/Delete.cshtml
@model CrudCliente.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Remoção de Clientes</h1>
<hr/>


<div>
    <h4>Remover Cliente</h4>
    <hr />
    <dl class="col">

        <div class="row">
            <dt class = "col-2">
                @Html.DisplayNameFor(model => model.Nome)
            </dt>
            <dd class = "col-10">
                @Html.DisplayFor(model => model.Nome)
            </dd>
        </div>

        <div class="row">
            <dt class = "col-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class = "col">
                @Html.DisplayFor(model => model.Email)
            </dd>
        </div>
        
        <div class="row">
            <dt class = "col-2">
                @Html.DisplayNameFor(model => model.Endereco)
            </dt>
            <dd class = "col">
                @Html.DisplayFor(model => model.Endereco)
            </dd>
        </div>

        <div class="row">
            <dt class = "col-2">
                @Html.DisplayNameFor(model => model.Contato)
            </dt>
            <dd class = "col-10">
                @Html.DisplayFor(model => model.Contato)
            </dd>
        </div>

        
    </dl>
    
    <form asp-action="Delete" class="grid gap-3 row">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger p-2 w-25" /> 
        <a asp-action="Index" class="btn btn-outline-primary p-2 g-col-3 w-25">Voltar</a>
    </form>
</div>

CrudCliente/Views/Clientes/Details.cshtml
@model CrudCliente.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1 class="mb-3">Detalhes do Cliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="col">
        <div class="row">
            <dt class="col-sm-1">
                @Html.DisplayNameFor(model => model.Nome):
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Nome)
            </dd>
        </div>
        <div class="row">
            <dt class = "col-sm-1">
                @Html.DisplayNameFor(model => model.Email):
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
        </div>
        <div class="row">
            <dt class = "col-sm-1">
                @Html.DisplayNameFor(model => model.Endereco):
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Endereco)
            </dd>
        </div>
        <div class="row">
            <dt class = "col-sm-1">
                @Html.DisplayNameFor(model => model.Contato):
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Contato)
            </dd>
        </div>
    </dl>
</div>
<div class="grid gap-3 row">
    <a asp-action="Edit" asp-route-id="@Model?.ID" class="btn btn-primary p-2 g-col-3 w-25">Editar</a> 
    <a asp-action="Index" class="btn btn-outline-primary p-2 g-col-3 w-25">Voltar</a>
</div>

CrudCliente/Views/Clientes/Edit.cshtml
@model CrudCliente.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1 class="mb-3">Edição de Cliente</h1>

<h4>Editar Cliente</h4>
<hr />
<div class="row">
    <div class="d-grid gap-3">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="input-group p-3 col gap-3 d-grid">
                
                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Nome" class="input-group-text"></label>
                    <input asp-for="Nome" class="form-control" />
                </div>
                
                <span asp-validation-for="Nome" class="text-danger"></span>
                
                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Email" class="input-group-text"></label>
                    <input asp-for="Email" class="form-control" />
                </div>
                
                <span asp-validation-for="Email" class="text-danger"></span>
                
                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Endereco" class="input-group-text"></label>
                    <input asp-for="Endereco" class="form-control" />
                </div>
                
                <span asp-validation-for="Endereco" class="text-danger"></span>
                
                <div class="input-group col-6 d-flex flex-row w-50">
                    <label asp-for="Contato" class="input-group-text"></label>
                    <input asp-for="Contato" class="form-control" />
                </div>
                
                <span asp-validation-for="Contato" class="text-danger"></span>
            
            </div>

            <div class="grid gap-3 row">
                <input type="submit" value="Salvar" class="btn btn-primary p-2 g-col-3 w-25" />
                <a asp-action="Index" class="btn btn-outline-primary p-2 g-col-3 w-25">Voltar </a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudCliente/Views/Clientes/Index.cshtml
@model IEnumerable<CrudCliente.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}
<div class="d-flex flex-wrap flex-row align-items-center gap-3">
    
    <h1 class="">Lista de Clientes </h1>
        <a asp-action="Create" class="btn btn-outline-dark">Inserir Cliente</a>

</div>

<table class="table" id="table-client">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contato)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contato)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">
                        <img class="index-icon" src="https://www.svgrepo.com/show/522527/edit-3.svg" alt="icon">
                </a> |
                <a asp-action="Details" asp-route-id="@item.ID">
                        <img class="index-icon" src="https://www.svgrepo.com/show/433410/details-so.svg" alt="icon">
                </a> |
                <a asp-action="Delete" asp-route-id="@item.ID">
                        <img class="index-icon" src="https://www.svgrepo.com/show/433400/delete-o.svg" alt="icon">
                </a>
            </td>
        </tr>
}
    </tbody>
</table>

CrudCliente/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="d-flex flex-column gap-4 align-items-center justify-content-center">
<div class="text-center">
    <h1 class="display-4">Sistema de Cadastro Para Clientes</h1>
    <a asp-controller="Clientes" class="btn btn-outline-primary m-4 g-col-3 w-25"> Iniciar Cadastro </a>
</div>
    <img class="m-3 w-75" src="https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="imagem de pessoas sentadas a mesa"></img>
</div>

CrudCliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudCliente</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudCliente.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/v/dt/dt-2.0.0/datatables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudCliente</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="index">Tabela Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrudCliente - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.0/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>